apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i-java-build-and-deploy
spec:
  workspaces:
    - name: source
  params:
    - name: git-url
      type: string
      description: The url of the git repository
    - name: git-revision
      type: string
      description: The git revision (branch, tag, or commit SHA)
      default: main
    - name: image-name
      type: string
      description: Name of the application image to build
    - name: app-name
      type: string
      description: Name of the OpenShift DeploymentConfig to update
  steps:
    - name: s2i-build
      image: registry.redhat.io/openjdk/openjdk-17-rhel8:latest
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - |
          s2i build $(params.git-url) --context-dir=. --ref=$(params.git-revision) -e MAVEN_OPTS="-Xmx512m" -Dquarkus.profile=prod -Dquarkus.package.type=fast-jar $(params.image-name):latest
      env:
        - name: BUILDER_VERSION
          value: "latest"
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2/repository
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - |
          oc project andersonaugustinho-dev # <<<<<<< SUBSTITUA PELO SEU NOME DE PROJETO NO SANDBOX (geralmente é andersonaugustinho-dev)
          oc set image deploymentconfig/$(params.app-name) $(params.app-name)=$(params.image-name):latest --dry-run=true -o yaml | oc apply -f -
          oc rollout status deploymentconfig/$(params.app-name) -w
  volumes:
    - name: maven-repo
      emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-cicd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: The url of the git repository
    - name: git-revision
      type: string
      description: The git revision (branch, tag, or commit SHA)
      default: main
  tasks:
    - name: build-and-deploy-app
      taskRef:
        name: s2i-java-build-and-deploy
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: image-name
          value: image-registry.openshift-image-registry.svc:5000/andersonaugustinho-dev/task-manager # <<<<<<< SUBSTITUA andersonaugustinho-dev PELO SEU NOME DE PROJETO
        - name: app-name
          value: task-manager # NOME DO SEU DEPLOYMENTCONFIG NO OpenShift (geralmente task-manager)