apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i-java-build-and-deploy
spec:
  workspaces:
    - name: source
  params:
    - name: git-url
      type: string
      description: The url of the git repository
    - name: git-revision
      type: string
      description: The git revision (branch, tag, or commit SHA)
      default: main
    - name: image-name
      type: string
      description: Name of the application image to build
    - name: app-name
      type: string
      description: Name of the OpenShift DeploymentConfig to update
  steps:
    - name: s2i-build
      image: registry.redhat.io/openshift-pipelines/s2i-java-container-image-rhel8:1.0 # IMPORTANTE: Verifique se esta imagem é compatível. Versão 17 ou 21 pode ser mais comum.
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Starting S2I build for $(params.image-name)..."
          # O S2I constrói a imagem e a envia para o registry interno.
          # Usamos -e MAVEN_OPTS para garantir memória suficiente para o build.
          s2i build $(params.git-url) --context-dir=. --ref=$(params.git-revision) -e MAVEN_OPTS="-Xmx1024m" -Dquarkus.profile=prod -Dquarkus.package.type=fast-jar $(params.image-name):latest
      # Adicione esta seção de env (ambiente) para a Task
      env:
        - name: BUILDER_VERSION
          value: "latest" # Versão do builder, pode ser "17" ou "21"
      volumeMounts:
        - name: maven-repo
          mountPath: /root/.m2/repository
    - name: deploy
      image: quay.io/openshift/origin-cli:latest # Imagem com o CLI 'oc'
      workingdir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Deploying $(params.app-name)..."
          # O `oc set image` atualiza o DeploymentConfig para usar a nova imagem.
          # --dry-run=true -o yaml | oc apply -f - é um truque para aplicar a mudança de forma idempotente.
          oc project andersonaugustinho-dev # <<<<<<< SUBSTITUA PELO SEU NOME DE PROJETO NO SANDBOX
          oc set image deploymentconfig/$(params.app-name) $(params.app-name)=$(params.image-name):latest --dry-run=true -o yaml | oc apply -f -
          # Espera o novo rollout completar antes de finalizar a Task
          oc rollout status deploymentconfig/$(params.app-name) -w
  # Define um volume vazio temporário para o cache Maven, para builds mais rápidos
  volumes:
    - name: maven-repo
      emptyDir: {}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-cicd-pipeline
spec:
  workspaces:
    - name: shared-workspace # Workspace para compartilhar entre Tasks (ex: código fonte)
  params:
    - name: git-url
      type: string
      description: The url of the git repository
    - name: git-revision
      type: string
      description: The git revision (branch, tag, or commit SHA)
      default: main
  tasks:
    - name: build-and-deploy-app
      taskRef:
        name: s2i-java-build-and-deploy # Referencia a Task que definimos acima
      workspaces:
        - name: source
          workspace: shared-workspace # Mapeia o workspace da Task para o workspace do Pipeline
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: image-name
          # <<<<<<< SUBSTITUA andersonaugustinho-dev PELO SEU NOME DE PROJETO
          value: image-registry.openshift-image-registry.svc:5000/andersonaugustinho-dev/task-manager 
        - name: app-name
          value: task-manager # <<<<<<< NOME DO SEU DEPLOYMENTCONFIG NO OpenShift